schema_version: 1

context:
  name: devtools
  version: 0.12.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/devtools-${{ version }}.tar.gz
  sha256: efceab184cb35e3a11fa8e602cc4fadacaa2e859e920fc6f87bf130b69885507

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - executing >=1.1.1
    - asttokens >=2.0.0,<3.0.0
    - pygments >=2.15.0

tests:
  - python:
      imports:
        - devtools
        - devtools.ansi
        - devtools.debug
        - devtools.prettier
        - devtools.timer
        - devtools.utils
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  summary: "Python's missing debug print command, and more."
  license: MIT
  license_file: LICENSE
  homepage: https://python-devtools.helpmanual.io
  repository: https://github.com/samuelcolvin/python-devtools

extra:
  recipe-maintainers:
    - Saransh-cpp
